//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_DETAILS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT_DETAILS()
        {
            this.PRODUCT_CATEGORY = new HashSet<PRODUCT_CATEGORY>();
        }
    
        public int Product_Detail_ID { get; set; }
        public int Product_Quantity { get; set; }
        public int Product_Price { get; set; }
        public Nullable<int> Product_Discount { get; set; }
        public Nullable<int> Product_Sold { get; set; }
        public Nullable<int> Product_Avaliable { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> ProductID { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT_CATEGORY> PRODUCT_CATEGORY { get; set; }
    }
}
