//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_CATEGORY
    {
        public int Product_Category_ID { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public Nullable<int> Category_ID { get; set; }
        public Nullable<int> Product_Detail_ID { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual PRODUCT_DETAILS PRODUCT_DETAILS { get; set; }
    }
}
